name: Smoke Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-smoke-test-${{ hashFiles('smoke_test.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-smoke-test-
          ${{ runner.os }}-pip-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxml2-dev \
          libxslt-dev \
          zlib1g-dev \
          libjpeg-dev \
          libfreetype6-dev \
          liblcms2-dev \
          libwebp-dev \
          tcl8.6-dev \
          tk8.6-dev \
          python3-tk
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy vectorbt ta-lib psutil tqdm
        pip install pytest pytest-cov
    
    - name: Run smoke test
      run: |
        python smoke_test.py
    
    - name: Upload smoke test logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: smoke-test-logs-${{ github.run_number }}
        path: |
          logs/
        retention-days: 30
    
    - name: Create smoke test summary
      run: |
        echo "## Smoke Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Python Version**: ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Logs**: [Download logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
    
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          const botComment = comments.find(comment => 
            comment.body.includes('Smoke Test Results')
          );
          
          const status = '${{ job.status }}' === 'success' ? '✅' : '❌';
          const comment = `${status} **Smoke Test Results**
          
          - **Status**: ${{ job.status }}
          - **Python Version**: ${{ matrix.python-version }}
          - **Commit**: \`${{ github.sha }}\`
          - **Logs**: [Download logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          ---
          *This comment was automatically generated by the CI pipeline.*
          `;
          
          if (botComment) {
            await github.rest.issues.updateComment({
              comment_id: botComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }